### ISSUE TITLE
asl checkbox flashes for a second and then disappears

### ISSUE THREAD

**Issue by sloucher** [meitar/fetlife-aslsearch#27]
Asl checkbox flashes for a second and then disappears. Couldn't find it again. I've disabled all add-ons other than greasemonkey.

**Comment by ljohnso16** [comment]
I bet its because fetlife changed the headers HTML to have the valentines day logo

**Comment by ekeyte** [comment]
I am also having this issue.

**Comment by CheeseburgerWithFries** [comment]
I'm experiencing this issue as well.

I had been using 0.3.9 for about ten months with no problems and used the same cautious search settings for that period (7 second delay / 70 results per search). Last week my account was disabled at about the same time someone [opened an issue here about how they were detected](https://github.com/meitar/fetlife-aslsearch/issues/26) and disabled as well.

I was able to regain access to my account after a couple days without admitting to the caretakers/support that I was using an add-on, but that's when I began experiencing this issue. I was still using 0.3.9 when this started.

I updated to 0.4.4.4 (current master) a couple days ago, but that did not correct the issue. The checkbox is still flashing up for a second and then disappearing.

Due to the recent issues people are having, I'd guess that Fetlife made some updates to the site code or their add-on detection last week, but I _do not_ have evidence to support this.

**Comment by ljohnso16** [comment]
I'm assuming because I really don't know how fet is checking or the script is injecting but: 
they must be adding an extra JS check that looks for the class names of the ASL extra area, then clears it with more js? this would make sense from the "flashing effect", we see the page load finish, then Greasemonkey injects, then fet removes?

Is there anyway, we can make the IDs and class names unique on every load?

**Comment by bgood66** [comment]
I have a same problem here !!

**Comment by bluehatter** [comment]
Good to know I'm not the only one having this problem. With the "extended" version I have different experiences on my PC and laptop... On my PC, which is currently running Windows 7 with Firefox, nothing appears at all on Fetlife, but on my laptop (which has Windows 10) a check box will briefly appear and then disappear. 

With the classic version of the script, the not "extended" version, on both computers some text that says "ASL search?" appears at the top of the web page but there is nothing to click on, it's just text. Both things happen on Chrome as well. 

I also had my account temporarily deactivated around a week or so ago and sent an E-mail asking what was going on. I never got any reply but my account was active again the next morning. I never thought about it, but it was after this that the script stopped working so it could very well be that Fetlife increased security or something. 

It's a shame, really. I really enjoyed this script. Thanks to the script I was able to make a couple local friends and I liked being able to find local people that shared some of my interests to chat with. I really miss the script...

**Comment by meitar** [comment]
This is fixed in f7ad8b2e8b536abaada6566f8572314e3dfcbc73, released as version 0.4.5. If you have a recent version of this script, it will automatically update. If you don't, you should uninstall and [re-install this script by clicking here](https://github.com/meitar/fetlife-aslsearch/raw/master/fetlife-age-sex-location-search.user.js).

**Comment by quasi8** [comment]
How about fetlife's detection of the script? Has this been addressed also?

**Comment by meitar** [comment]
> How about fetlife's detection of the script? Has this been addressed also?

Only one way to find out, and of the two of us, I'm not the one who uses FetLife. ;)

**Comment by izadorr** [comment]
I am having this problem too and I did re-install the script. I never used it before (have never gotten to use it yet)

**Comment by meitar** [comment]
Try updating to version 0.4.6, which contains another attempted fix for this issue that works for Google Chrome users. Seems to work in my testing.

**Comment by Typhotic** [comment]
Hello, the search stopped working for me in both Chrome and Firefox. It worked at first but it stopped working on both all at once. The search bar finishes but no results ever get displayed. 

I am guessing it is fetlife doing something because I recently did a fresh windows install and it still isn't working. 

I am on .0.4.6>

Thanks!
