### ISSUE TITLE
Extended edition in Google Chrome opens in new tab/does not load at all in Firefox

### ISSUE THREAD

**Issue by ImBrianHello** [meitar/fetlife-aslsearch#6]
The Google script opens in a new tab using Google Chrome, not on the same webpage. Intended?

When using Firefox, the Google script doesn't even load. A blank space in displayed where it should be. There is the 'Enlarge' button, which tries to make the script full screen as intended, but there's nothing to display except the 'Close FetLife ASL Search' button.

**Comment by meitar** [comment]
I can't reproduce this issue. Opening in a new tab in Chrome is intended behavior, so that's not a bug. Not loading in Firefox would be a bug, but it does load for me, so I don't know why it's not working for you.

As per usual, please ensure you're using the latest version of Mozilla Firefox, the latest version of Greasemonkey, and that any other extensions/plugins/user-scripts/etc. are not conflicting with this one.

If you're still having issues, please read [How to write a good bug report](http://noverse.com/blog/2012/06/how-to-write-a-good-bug-report/) and copy the template they provide into the [new issue](https://github.com/meitar/fetlife-aslsearch/issues/new) form when filing a new issue to ensure your bug report is complete and usefully informational.

**Comment by meitar** [comment]
The best bug report for this issue so far is in #9, see that thread for further info.

**Comment by meitar** [comment]
@ImBrianHello, out of curiosity, what operating system and version of it are you running? (Windows, Mac, etc?)
